heat_template_version: 2013-05-23

description: 
  A HOT template that creates VM instance with an attached Cinder volume.

parameters:
  key_name:
    type: string
    description: Name of an existing key pair to use for the instance
    default: heat_key
  flavor:
    type: string
    description: Flavor for the instance to be created
    default: c1.medium
  image:
    type: string
    description: Name or ID of the image to use for the instance.
    default: Standard_openSUSE_42_JeOS_latest
  network:
    type: string
    description: The network for the VM
  vol_size:
    type: number
    description: The size of the Cinder volume
    default: 50

resources:
  my_instance:
    type: OS::Nova::Server
    properties:
      key_name: { get_param: key_name }
      image: { get_param: image }
      flavor: { get_param: flavor }
      networks: 
        - network: { get_param: network }
      user_data_format: RAW

  my_vol:
    type: OS::Cinder::Volume
    properties:
      size: { get_param: vol_size }

  vol_att:
    type: OS::Cinder::VolumeAttachment
    properties:
      instance_uuid: { get_resource: my_instance }
      volume_id: { get_resource: my_vol }
      mountpoint: /dev/vdb

outputs:
  instance_networks:
    description: The IP addresses of the deployed instance
    value: { get_attr: [my_instance, networks] }
